# SLURM specific stuff
executor: slurm
default-resources:
  threads: 1
  slurm_account: None   # CHANGE
  slurm_partition: None # CHANGE
slurm-requeue: True
slurm-status-command: sacct

# Conda stuff
use-conda: True
conda-frontend: conda
conda-prefix: /path/to/dir/for/conda/envs  # CHANGE

# Singularity/Apptainer stuff
# use-singularity: True

# General stuff
jobs: 100
latency-wait: 240
restart-times: 3
keep-going: True
rerun-incomplete: True
printshellcmds: True
show-failed-logs: True

